export const navItemsByRole = {
  Admin: [
    { to: '/admin/dashboard', end: true, icon: 'chart', label: 'Dashboard' },
    { type: 'label', label: 'Operação' },
    { to: '/admin', end: true, icon: 'cal', label: 'Agenda' },
    { to: '/admin/agendamentos', icon: 'receipt', label: 'Agendamentos' },
    { to: '/admin/usuarios', icon: 'users', label: 'Usuários' },
    { to: '/admin/servicos', icon: 'scissors', label: 'Serviços' },
    { to: '/admin/combos', icon: 'package', label: 'Pacotes' },
    { to: '/admin/convidar-profissional', icon: 'plus', label: 'Convidar profissional' },
    { type: 'label', label: 'Financeiro' },
    { to: '/admin/caixa', icon: 'receipt', label: 'Comandas' },
    { to: '/admin/produtos', icon: 'tag', label: 'Produtos' },
    { to: '/admin/pedidos-produtos', icon: 'cash', label: 'Pedidos de Produtos' },
    { type: 'label', label: 'Conta' },
    { to: '/profissional/servicos', icon: 'scissors', label: 'Meus serviços' },
    { to: '/profissional/horarios', icon: 'clock', label: 'Meus horários' },
    { to: '/perfil', icon: 'users', label: 'Meu perfil' },
  ],
  Profissional: [
    { to: '/profissional', end: true, icon: 'cal', label: 'Minha agenda' },
    { to: '/profissional/agendamentos', icon: 'receipt', label: 'Agendamentos' },
    { to: '/profissional/comissoes', icon: 'cash', label: 'Minhas comissões' },
    { to: '/profissional/servicos', icon: 'scissors', label: 'Meus serviços' },
    { to: '/profissional/horarios', icon: 'clock', label: 'Meus horários' },
    { type: 'label', label: 'Conta' },
    { to: '/perfil', icon: 'users', label: 'Meu perfil' },
  ],
  Usuario: [
    { to: '/cliente', end: true, icon: 'cal', label: 'Início' },
    { to: '/cliente/agendamentos', icon: 'receipt', label: 'Meus agendamentos' },
    { to: '/cliente/combos', icon: 'package', label: 'Meus combos' },
    { to: '/cliente/comandas', icon: 'cash', label: 'Minhas comandas' },
    { to: '/perfil', icon: 'users', label: 'Perfil e senha' },
  ],
}
